import jsPDF from "jspdf";

interface MaintenanceRecordLite {
  service_type: string;
  service_date: string; // YYYY-MM-DD
  mileage: number | null;
  cost: number | null;
  notes: string | null;
  attachments?: { id: string }[];
}

interface CarLite {
  name?: string | null;
  year?: number | string | null;
  make?: string | null;
  model?: string | null;
}

interface ExportOptions {
  car: CarLite | undefined;
  records: MaintenanceRecordLite[];
}

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "vehicle";

const fmtMoney = (n: number) =>
  `$${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const fmtDate = (iso: string) => {
  const d = new Date(iso + "T00:00:00");
  return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
};

const MARGIN = 48;
const FOOTER_HEIGHT = 28;
const HEADER_HEIGHT = 56;
const ENTRY_GAP = 10;

export const exportMaintenanceToPdf = ({ car, records }: ExportOptions) => {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageBottom = pageHeight - FOOTER_HEIGHT - MARGIN / 2;
  const contentWidth = pageWidth - MARGIN * 2;

  const vehicleLine = car
    ? [car.year, car.make, car.model].filter(Boolean).join(" ") || car.name || "Vehicle"
    : "Vehicle";
  const carName = car?.name || vehicleLine;

  // ----- Stats -----
  const total = records.length;
  const totalSpent = records.reduce((s, r) => s + (r.cost || 0), 0);
  const sortedByDate = [...records].sort((a, b) => a.service_date.localeCompare(b.service_date));
  const earliest = sortedByDate[0]?.service_date;
  const latest = sortedByDate[sortedByDate.length - 1]?.service_date;
  const recordsWithMileage = records.filter((r) => r.mileage != null);
  const latestMileage = recordsWithMileage.length
    ? recordsWithMileage.sort((a, b) => b.service_date.localeCompare(a.service_date))[0].mileage
    : null;

  // By year
  const byYearMap = new Map<string, { count: number; total: number }>();
  for (const r of records) {
    const year = r.service_date.slice(0, 4);
    const cur = byYearMap.get(year) || { count: 0, total: 0 };
    cur.count++;
    cur.total += r.cost || 0;
    byYearMap.set(year, cur);
  }
  const byYear = Array.from(byYearMap.entries())
    .map(([year, v]) => ({ year, ...v }))
    .sort((a, b) => b.year.localeCompare(a.year));

  // By service type
  const byTypeMap = new Map<string, { count: number; total: number }>();
  for (const r of records) {
    const cur = byTypeMap.get(r.service_type) || { count: 0, total: 0 };
    cur.count++;
    cur.total += r.cost || 0;
    byTypeMap.set(r.service_type, cur);
  }
  const byType = Array.from(byTypeMap.entries())
    .map(([type, v]) => ({ type, ...v }))
    .sort((a, b) => b.total - a.total)
    .slice(0, 10);

  // ----- Header / footer -----
  const drawHeader = (isCover = false) => {
    if (isCover) return; // cover page draws its own big title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text("Maintenance Log", MARGIN, MARGIN);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(110);
    doc.text(vehicleLine, pageWidth - MARGIN, MARGIN, { align: "right" });
    doc.setDrawColor(220);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, MARGIN + 10, pageWidth - MARGIN, MARGIN + 10);
  };

  const drawFooter = (pageNum: number, totalPages: number) => {
    const today = new Date().toLocaleDateString();
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Generated by Track Side Ops • ${today}`, MARGIN, pageHeight - MARGIN / 2);
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth - MARGIN,
      pageHeight - MARGIN / 2,
      { align: "right" }
    );
  };

  // We'll render twice: first compute total page count by simulating, then render with footers.
  // Simpler approach: render to pages, track page count, then go back and stamp footers.
  type PageStamp = { pageIndex: number };
  const stamps: PageStamp[] = [];

  // ===== Cover Page =====
  let y = MARGIN;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(20);
  doc.text("Maintenance Log", MARGIN, y + 10);
  y += 36;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(60);
  doc.text(vehicleLine, MARGIN, y);
  y += 18;

  if (carName && carName !== vehicleLine) {
    doc.setFontSize(11);
    doc.setTextColor(110);
    doc.text(carName, MARGIN, y);
    y += 14;
  }

  doc.setFontSize(10);
  doc.setTextColor(130);
  doc.text(`Generated ${new Date().toLocaleDateString()}`, MARGIN, y);
  y += 22;

  doc.setDrawColor(220);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 18;

  // Overall stats
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30);
  doc.text("Overview", MARGIN, y);
  y += 16;

  const drawStat = (label: string, value: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(110);
    doc.text(label, MARGIN, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20);
    doc.text(value, MARGIN + 180, y);
    y += 14;
  };

  drawStat("Total records", String(total));
  drawStat("Total spent", fmtMoney(totalSpent));
  if (earliest && latest) {
    drawStat("Date range", `${fmtDate(earliest)} – ${fmtDate(latest)}`);
  }
  if (latestMileage != null) {
    drawStat("Latest mileage", `${latestMileage.toLocaleString()} mi`);
  }
  y += 10;

  // Helpers for tables
  const drawTable = (
    heading: string,
    columns: { header: string; width: number; align?: "left" | "right" }[],
    rows: string[][]
  ) => {
    if (rows.length === 0) return;
    if (y + 60 > pageBottom) {
      stamps.push({ pageIndex: doc.getNumberOfPages() });
      doc.addPage();
      drawHeader();
      y = MARGIN + HEADER_HEIGHT;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(30);
    doc.text(heading, MARGIN, y);
    y += 14;

    // Header row
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(90);
    let x = MARGIN;
    columns.forEach((c) => {
      doc.text(c.header, c.align === "right" ? x + c.width : x, y, {
        align: c.align === "right" ? "right" : "left",
      });
      x += c.width;
    });
    y += 6;
    doc.setDrawColor(220);
    doc.line(MARGIN, y, MARGIN + columns.reduce((s, c) => s + c.width, 0), y);
    y += 10;

    // Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30);
    for (const row of rows) {
      if (y + 14 > pageBottom) {
        stamps.push({ pageIndex: doc.getNumberOfPages() });
        doc.addPage();
        drawHeader();
        y = MARGIN + HEADER_HEIGHT;
      }
      let cx = MARGIN;
      row.forEach((cell, i) => {
        const col = columns[i];
        doc.text(cell, col.align === "right" ? cx + col.width : cx, y, {
          align: col.align === "right" ? "right" : "left",
        });
        cx += col.width;
      });
      y += 14;
    }
    y += 12;
  };

  if (byYear.length > 0) {
    drawTable(
      "Spend by Year",
      [
        { header: "Year", width: 100 },
        { header: "Records", width: 100, align: "right" },
        { header: "Total Spent", width: contentWidth - 200, align: "right" },
      ],
      byYear.map((r) => [r.year, String(r.count), fmtMoney(r.total)])
    );
  }

  if (byType.length > 0) {
    drawTable(
      "Top Service Types by Spend",
      [
        { header: "Service Type", width: contentWidth - 200 },
        { header: "Count", width: 80, align: "right" },
        { header: "Total", width: 120, align: "right" },
      ],
      byType.map((r) => [r.type, String(r.count), fmtMoney(r.total)])
    );
  }

  // ===== Detail pages =====
  stamps.push({ pageIndex: doc.getNumberOfPages() }); // close cover (and overflow) pages
  doc.addPage();
  drawHeader();
  y = MARGIN + HEADER_HEIGHT;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(20);
  doc.text("Service History", MARGIN, y);
  y += 20;

  if (records.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.setTextColor(140);
    doc.text("(No service records)", MARGIN, y);
  } else {
    const sorted = [...records].sort((a, b) => b.service_date.localeCompare(a.service_date));

    // Auto-fit body font: 11 if it fits comfortably, else 10, else 9
    const measureBody = (fontSize: number) => {
      doc.setFontSize(fontSize);
      const lh = fontSize * 1.3;
      let yy = y;
      let pages = 1;
      const usableTop = MARGIN + HEADER_HEIGHT + 20;
      for (const r of sorted) {
        const noteLines = r.notes
          ? (doc.splitTextToSize(r.notes, contentWidth) as string[])
          : [];
        const entryHeight =
          lh /* title row */ +
          lh /* meta row */ +
          (noteLines.length ? noteLines.length * lh + 4 : 0) +
          ENTRY_GAP;
        if (yy + entryHeight > pageBottom) {
          pages++;
          yy = usableTop;
        }
        yy += entryHeight;
      }
      return pages;
    };

    let bodyFont = 11;
    const p11 = measureBody(11);
    if (p11 > 1) {
      const p10 = measureBody(10);
      bodyFont = p10 < p11 ? 10 : 11;
      if (p10 > 1) {
        const p9 = measureBody(9);
        if (p9 < p10) bodyFont = 9;
      }
    }

    const lh = bodyFont * 1.3;
    const usableTop = MARGIN + HEADER_HEIGHT + 20;

    for (const r of sorted) {
      const noteLines = r.notes
        ? (doc.splitTextToSize(r.notes, contentWidth) as string[])
        : [];
      const entryHeight =
        lh + lh + (noteLines.length ? noteLines.length * lh + 4 : 0) + ENTRY_GAP;

      if (y + entryHeight > pageBottom) {
        stamps.push({ pageIndex: doc.getNumberOfPages() });
        doc.addPage();
        drawHeader();
        y = MARGIN + HEADER_HEIGHT;
      }

      // Title row: service type + cost (right)
      doc.setFont("helvetica", "bold");
      doc.setFontSize(bodyFont + 1);
      doc.setTextColor(20);
      doc.text(r.service_type, MARGIN, y);
      if (r.cost != null) {
        doc.text(fmtMoney(r.cost), pageWidth - MARGIN, y, { align: "right" });
      }
      y += lh;

      // Meta row: date · mileage · attachments
      const metaParts: string[] = [fmtDate(r.service_date)];
      if (r.mileage != null) metaParts.push(`${r.mileage.toLocaleString()} mi`);
      const attCount = r.attachments?.length || 0;
      if (attCount > 0) metaParts.push(`${attCount} attachment${attCount === 1 ? "" : "s"}`);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(bodyFont);
      doc.setTextColor(110);
      doc.text(metaParts.join("  ·  "), MARGIN, y);
      y += lh;

      if (noteLines.length) {
        doc.setTextColor(50);
        doc.text(noteLines, MARGIN, y);
        y += noteLines.length * lh;
      }

      y += ENTRY_GAP;
    }
  }

  // ===== Stamp footers on all pages =====
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  const filename = `maintenance-log-${slugify(carName)}-${new Date()
    .toISOString()
    .slice(0, 10)}.pdf`;
  doc.save(filename);
};