import jsPDF from "jspdf";

interface ChecklistItem {
  text: string;
  completed?: boolean;
}

interface ExportChecklistOptions {
  title: string;
  type: "event" | "trailer" | string;
  mode?: "template" | "event";
  items: ChecklistItem[];
  eventName?: string;
  eventDate?: string;
}

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "checklist";

export const exportChecklistToPdf = (opts: ExportChecklistOptions) => {
  const { title, type, mode = "template", items, eventName, eventDate } = opts;
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, margin, y);
  y += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(110);
  const typeLabel = type.charAt(0).toUpperCase() + type.slice(1);
  let subtitle = `${typeLabel} checklist`;
  if (eventName) subtitle += `  •  ${eventName}`;
  if (eventDate) subtitle += `  •  ${eventDate}`;
  doc.text(subtitle, margin, y);
  y += 10;

  doc.setDrawColor(200);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 18;

  doc.setTextColor(20);
  doc.setFontSize(12);

  if (items.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setTextColor(140);
    doc.text("(No items in this checklist)", margin, y);
    y += 16;
  } else {
    const boxSize = 12;
    const lineHeight = 20;
    const textX = margin + boxSize + 10;
    const textWidth = pageWidth - textX - margin;

    items.forEach((item) => {
      if (y + lineHeight > pageHeight - margin - 30) {
        doc.addPage();
        y = margin;
      }

      doc.setDrawColor(80);
      doc.setLineWidth(0.8);
      doc.rect(margin, y - boxSize + 2, boxSize, boxSize);

      if (mode === "event" && item.completed) {
        doc.setLineWidth(1.4);
        doc.line(margin + 2, y - 3, margin + 5, y);
        doc.line(margin + 5, y, margin + boxSize - 1, y - boxSize + 3);
      }

      doc.setFont("helvetica", "normal");
      doc.setTextColor(mode === "event" && item.completed ? 140 : 20);
      const lines = doc.splitTextToSize(item.text, textWidth);
      doc.text(lines, textX, y);
      y += Math.max(lineHeight, lines.length * 14 + 6);
    });
  }

  const today = new Date().toLocaleDateString();
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(`Generated by Track Side Ops • ${today}`, margin, pageHeight - margin / 2);

  const filename = `checklist-${slugify(title)}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
};