import jsPDF from "jspdf";

interface ChecklistItem {
  text: string;
  completed?: boolean;
}

interface ExportChecklistOptions {
  title: string;
  type: "event" | "trailer" | string;
  mode?: "template" | "event";
  items: ChecklistItem[];
  eventName?: string;
  eventDate?: string;
}

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "checklist";

// Tunables for auto-fit
const MIN_FONT = 9;
const MAX_FONT = 13;
const MARGIN = 48;
const HEADER_HEIGHT = 70; // title + subtitle + divider
const FOOTER_HEIGHT = 28;
const ITEM_GAP = 6; // vertical gap between items

export const exportChecklistToPdf = (opts: ExportChecklistOptions) => {
  const { title, type, mode = "template", items, eventName, eventDate } = opts;
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableHeight = pageHeight - MARGIN - FOOTER_HEIGHT - HEADER_HEIGHT;
  const typeLabel = type.charAt(0).toUpperCase() + type.slice(1);

  // ----- Auto-fit: pick the largest font where everything renders in fewest pages -----
  // Strategy: try MAX_FONT down to MIN_FONT; first size whose total page count fits the
  // "ideal" page count (computed at MIN_FONT) wins. We always honor item-atomic page breaks.
  const measure = (fontSize: number) => {
    doc.setFontSize(fontSize);
    const lineHeight = fontSize * 1.25;
    const boxSize = Math.max(10, fontSize);
    const textX = MARGIN + boxSize + 10;
    const textWidth = pageWidth - textX - MARGIN;
    let pages = 1;
    let cursor = 0; // y offset within usable area on current page

    for (const item of items) {
      const lines = doc.splitTextToSize(item.text || " ", textWidth) as string[];
      const itemHeight = Math.max(lineHeight, lines.length * lineHeight) + ITEM_GAP;
      // If it doesn't fit on current page (and isn't the very first item), break
      if (cursor > 0 && cursor + itemHeight > usableHeight) {
        pages++;
        cursor = 0;
      }
      // If a single item is taller than a full page (edge case), it still consumes one
      cursor += itemHeight;
    }
    return { pages, lineHeight, boxSize, textX, textWidth };
  };

  // Find smallest possible page count, then use the largest font that achieves it.
  let bestFont = MIN_FONT;
  let bestMetrics = measure(MIN_FONT);
  const minPages = bestMetrics.pages;

  for (let f = MAX_FONT; f >= MIN_FONT; f--) {
    const m = measure(f);
    if (m.pages <= minPages) {
      bestFont = f;
      bestMetrics = m;
      break;
    }
  }

  const { lineHeight, boxSize, textX, textWidth } = bestMetrics;

  // ----- Header / footer renderers -----
  const drawHeader = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(20);
    doc.text(title, MARGIN, MARGIN + 4);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(110);
    let subtitle = `${typeLabel} checklist`;
    if (eventName) subtitle += `  •  ${eventName}`;
    if (eventDate) subtitle += `  •  ${eventDate}`;
    doc.text(subtitle, MARGIN, MARGIN + 24);

    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, MARGIN + 36, pageWidth - MARGIN, MARGIN + 36);
  };

  const drawFooter = (pageNum: number, totalPages: number) => {
    const today = new Date().toLocaleDateString();
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Generated by Track Side Ops • ${today}`, MARGIN, pageHeight - MARGIN / 2);
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth - MARGIN,
      pageHeight - MARGIN / 2,
      { align: "right" }
    );
  };

  // ----- Render -----
  const totalPages = bestMetrics.pages;
  let pageNum = 1;
  drawHeader();
  let y = MARGIN + HEADER_HEIGHT;
  const pageBottom = pageHeight - FOOTER_HEIGHT - MARGIN / 2;

  if (items.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(bestFont);
    doc.setTextColor(140);
    doc.text("(No items in this checklist)", MARGIN, y);
  } else {
    doc.setFontSize(bestFont);

    for (const item of items) {
      const lines = doc.splitTextToSize(item.text || " ", textWidth) as string[];
      const itemHeight = Math.max(lineHeight, lines.length * lineHeight) + ITEM_GAP;

      // Atomic page break: never split an item across pages
      if (y > MARGIN + HEADER_HEIGHT && y + itemHeight > pageBottom) {
        drawFooter(pageNum, totalPages);
        doc.addPage();
        pageNum++;
        drawHeader();
        y = MARGIN + HEADER_HEIGHT;
      }

      // Checkbox (vertically centered against first text line)
      const boxY = y - boxSize + (lineHeight - boxSize) / 2 + 2;
      doc.setDrawColor(80);
      doc.setLineWidth(0.8);
      doc.rect(MARGIN, boxY, boxSize, boxSize);

      if (mode === "event" && item.completed) {
        doc.setLineWidth(1.4);
        doc.line(MARGIN + 2, boxY + boxSize * 0.55, MARGIN + boxSize * 0.4, boxY + boxSize - 2);
        doc.line(MARGIN + boxSize * 0.4, boxY + boxSize - 2, MARGIN + boxSize - 1, boxY + 2);
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(bestFont);
      doc.setTextColor(mode === "event" && item.completed ? 140 : 20);
      doc.text(lines, textX, y);

      y += itemHeight;
    }
  }

  drawFooter(pageNum, totalPages);

  const filename = `checklist-${slugify(title)}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
};