project_id = "fkkemgtdxbsqvtsidhvu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.flag-downlink-broadcast]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
