// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czrtttccfuhvomcwtmwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cnR0dGNjZnVodm9tY3d0bXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjI5MjYsImV4cCI6MjA2NzM5ODkyNn0.yd2kR2OSZhZg8a9PqR9LzCIWF69OUVVSDvdq8_5vpHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});